# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0f1844456a64bf157a06758ca92d69d98320585a7e8d8c602f789cde273488a0100302943f2750a27c63caa377a2a848978a1e55cf59a73460aa5fed93dcd9

test:
  secret_key_base: 6264c4ebf58df0239e7094d4b3f09f55f864043857cc7294801b19135faf5d1d73c08c7f2667cab0a083bd4633639f80b804fb5f46ffe421d454ad348399f7f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
